#!/bin/bash

# copies file(s) given as argument to file.YYYYMMDDhhmmss
if (( $# < 1 )); then
  echo "Usage: bkp <filename1> [filename2]"
  exit 1
fi

for i in "$@"; do
  cp -p $i $i.$(date +%Y%m%d%H%M%S).bkp
done
