#!/bin/bash

if (( $# < 1 )); then
  echo "Usage: togglehost <hostname>"
  exit 1
fi

HOST=$1
FILE=/etc/hosts
FILETMP=/tmp/hosts.bkp

cp $FILE $FILETMP
perl -pi -e "s/^#(\d+\.\d+\.\d+\.\d+\s+.*$HOST.*)/\$1/" $FILETMP
if diff $FILE $FILETMP > /dev/null ; then
  perl -pi -e "s/^(\d+\.\d+\.\d+\.\d+\s+.*$HOST.*)/#\$1/" $FILETMP
fi
colordiff $FILE $FILETMP
read -p "Replace /etc/hosts? (Y/n) " -n 1 -r
if [[ $REPLY =~ ^.$ ]] ; then
  echo
fi
if [[ $REPLY =~ ^[Yy]?$ ]] ; then
  sudo cp $FILETMP $FILE
fi
